### ISSUE TITLE
New repo and encountering issue in sqlfluff [WSL Ubuntu]

### ISSUE THREAD

**Issue by msnillo** [ashish10alex/vscode-dataform-tools#24]
Hi @ashish10alex,

Creating an issue again because I cannot use the formatting of sqlfluff via extension.
Here are the steps I took:
1. Opened the folder in the root of dataform repository
2. Ran dataform install & dataform init-creds bigquery - both were successful
3. Encountered the error of `sqlfluff not found`
<img width="243" alt="image" src="https://github.com/user-attachments/assets/67567e73-78b7-4f2b-91f6-b595aa4ebd69">

5. Also tried the reloading the VSCode window
6. Encountered the error of `sqlfluff cli not found in path` 
<img width="244" alt="image" src="https://github.com/user-attachments/assets/6ff83067-bc1b-4055-8d80-03695a446887">

7. But you can see in the image below that I have sqlfluff in .vscode-dataform-tools
<img width="284" alt="image" src="https://github.com/user-attachments/assets/0e6fa8d3-e463-40f0-a071-69beadd1b10f">

Would like to know if I did anything wrong?

Thanks!

**Comment by ashish10alex** [comment]
Hi @msnillo , 
Thanks for the detailed issue. The reason it shows the error is due to `sqlfluff` cli not being available in path. The latest version of the extension (`v0.0.50`) now just uses `sqlfluff` cli as its dependancy. You can resolve this issue by doing the following 

1. Open wsl terminal, ensure that you are NOT in a python virtual environment and run `pip uninstall sqlfluff` followed by `pip install sqlfluff`
2. Running (1) would show you where the pip installs the `sqfluff` cli. It will show you a warning that the installed binary is perhaps not in your system path. See screenshot attached. 
3. You can resolve this by adding the path to your system path by adding the highlighted path to your `~/.zshrc` or `~/.bashrc` file by running the following 

  ```bash
  export PATH=$PATH:/home/aalex/.local/bin
  ```
5. After doing the (3) either restart the terminal or source your `~/.zshrc` or `~/.bashrc` for the path addition to take effect 
6. Now you can confirm that `sqlfluff` is installed as expected by running `sqlfluff --version`. Following which formatting should work as expected 

Please do let me know if the above solves your issue

**Comment by msnillo** [comment]
Awesome, thank you! 
The issue has been fixed. I'll also close this issue.
